import { StyleSheet, Dimensions } from 'react-native';
import theme from './theme';

const { width: screenWidth } = Dimensions.get('window');

const styles = StyleSheet.create({
  flexOne: { flex: 1 },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: theme.background },
  baseContainer: { flex: 1, backgroundColor: theme.background },
  studyContainer: { flex: 1, backgroundColor: theme.background, justifyContent: 'center', alignItems: 'center' },
  glow: { position: 'absolute', opacity: 0, width: 100, height: '100%' },
  glowLeft: { left: 0, top: 0, bottom: 0 },
  glowRight: { right: 0, top: 0, bottom: 0 },
  glowTop: { top: 0, left: 0, right: 0, height: 100, width: '100%' },
  cardWrapper: { flex: 1, justifyContent: 'center', alignItems: 'center', width: '100%', height: '100%', marginBottom: 40 },
  itemContainer: { backgroundColor: theme.backgroundSecondary, padding: 20, marginVertical: 8, marginHorizontal: 16, borderRadius: 10, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  progressSubjectContainer: { backgroundColor: theme.backgroundSecondary, paddingHorizontal: 20, paddingVertical: 15, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  itemTextContainer: { flex: 1, marginRight: 16 },
  itemTitle: { fontSize: theme.fontSize.md, color: theme.textPrimary, fontWeight: theme.fontWeight.bold },
  itemSubtitle: { fontSize: theme.fontSize.body, color: theme.textMuted, marginTop: 4 },
  progressContainer: { width: 50, height: 50, borderRadius: 25, borderWidth: 3, borderColor: theme.primary, justifyContent: 'center', alignItems: 'center' },
  progressText: { color: theme.textPrimary, fontWeight: theme.fontWeight.bold },
  cardContainer: { position: 'absolute' },
  card: { width: screenWidth * 0.9, height: 460, backgroundColor: '#1C1C1E', borderRadius: 20, justifyContent: 'space-between', alignItems: 'stretch', padding: 0, backfaceVisibility: 'hidden', borderWidth: 1, borderColor: 'rgba(255,255,255,0.06)' },
  cardDominated: { borderColor: theme.primary, borderWidth: 1.5 },
  cardBack: { backgroundColor: '#161618', position: 'absolute', top: 0, justifyContent: 'space-between', backfaceVisibility: 'hidden' },
  cardOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#000000',
    borderRadius: 20,
  },
  cardContentScrollView: { flex: 1, width: '100%' },
  cardContent: { flexGrow: 1, justifyContent: 'center', alignItems: 'center', padding: 20, paddingTop: 75 },
  cardText: { fontSize: theme.fontSize.xl, color: theme.textPrimary, textAlign: 'center' },
  noCardsText: { fontSize: theme.fontSize.md, color: theme.textMuted, textAlign: 'center', paddingHorizontal: 20 },
  cardFooter: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, paddingHorizontal: 20, backgroundColor: 'rgba(0,0,0,0.2)', width: '100%' },
  levelCircle: { width: 70, height: 70, borderRadius: 35, justifyContent: 'center', alignItems: 'center', marginRight: 15, borderWidth: 2, borderColor: theme.background },
  levelText: { color: theme.textPrimary, fontWeight: theme.fontWeight.bold, fontSize: theme.fontSize.h1 },
  progressBarContainer: { height: 16, backgroundColor: theme.background, borderRadius: 50, overflow: 'hidden', justifyContent: 'center' },
  progressPercentageText: { position: 'absolute', alignSelf: 'center', color: theme.textPrimary, fontWeight: theme.fontWeight.bold, fontSize: theme.fontSize.xs },
  levelNamesContainer: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8 },
  levelName: { fontSize: theme.fontSize.caption, color: '#9CA3AF', fontWeight: theme.fontWeight.bold },
  swipeGuideContainer: { position: 'absolute', bottom: 32, left: 0, right: 0, alignItems: 'center' },
  swipeGuideText: { color: theme.textMuted, fontSize: theme.fontSize.base, fontWeight: theme.fontWeight.bold },
  feedbackText: { fontSize: theme.fontSize.xl, fontWeight: theme.fontWeight.bold, marginBottom: 20 },
  progressIndicator: { position: 'absolute', bottom: 20, alignItems: 'center' },
  userCreatedBanner: { backgroundColor: theme.backgroundSecondary, paddingHorizontal: 8, paddingVertical: 2, borderRadius: 6, marginBottom: 6 },
  userCreatedText: { color: theme.primary, fontSize: theme.fontSize.sm, fontWeight: theme.fontWeight.bold },
  fab: { position: 'absolute', width: 56, height: 56, alignItems: 'center', justifyContent: 'center', right: 20, bottom: 20, backgroundColor: theme.primary, borderRadius: 28, elevation: 8, shadowOpacity: 0.3, shadowRadius: 4, shadowOffset: { height: 2, width: 0 } },
  formContainer: { flex: 1, backgroundColor: theme.background, padding: 20 },
  formLabel: { fontSize: theme.fontSize.base, color: theme.textPrimary, marginBottom: 8, marginTop: 16 },
  formInput: {
    backgroundColor: theme.backgroundSecondary,
    color: theme.textPrimary,
    borderRadius: 8,
    padding: 12,
    fontSize: theme.fontSize.base,
    minHeight: 50,
    textAlignVertical: 'top'
  },
  mathInputContainerUnified: {
    minHeight: 200,
    flex: 1,
    backgroundColor: theme.backgroundSecondary,
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: theme.backgroundSecondary,
    marginBottom: 10,
  },
  mathInputContainerFocused: {
    borderColor: theme.primary,
  },
  webviewStyle: {
    flex: 1,
    backgroundColor: theme.backgroundSecondary,
    opacity: 0.99,
  },
  mathInputContainerUnifiedLarge: {
    minHeight: 180,
    flex: 1,
  },
  inputGroup: {
    marginBottom: 10,
    flex: 1,
  },
  bottomControlsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 15,
    marginBottom: 10,
    paddingHorizontal: 5,
  },
  saveButtonContainer: {
    flex: 1,
    marginLeft: 15,
  },
  fxButton: {
    backgroundColor: theme.backgroundTertiary,
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 15,
    alignSelf: 'center',
  },
  fxButtonActive: {
    backgroundColor: theme.primary,
  },
  fxButtonText: {
    color: theme.textPrimary,
    fontSize: theme.fontSize.md,
    fontWeight: theme.fontWeight.bold,
  },
  mathKeyboardOverlay: {
    backgroundColor: '#252E3D',
    borderTopWidth: 1,
    borderTopColor: theme.backgroundTertiary,
    paddingTop: 8,
  },
  mathToolbarContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    paddingHorizontal: 5,
    paddingBottom: 5,
  },
  mathToolbarButton: {
    backgroundColor: theme.backgroundTertiary,
    borderRadius: 8,
    paddingVertical: 10,
    margin: 4,
    minWidth: 48,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mathToolbarButtonText: {
    color: theme.textPrimary,
    fontSize: theme.fontSize.lg,
    fontWeight: theme.fontWeight.bold,
  },
  formContainerNoPadding: {
    flex: 1,
    backgroundColor: theme.background,
  },
  scrollContentContainer: {
    flexGrow: 1,
    padding: 20,
    justifyContent: 'flex-start',
  },
  progressTitle: { fontSize: theme.fontSize.xxl, color: theme.textPrimary, fontWeight: theme.fontWeight.bold },
  progressValue: { fontSize: theme.fontSize.display, color: theme.primary, fontWeight: theme.fontWeight.bold, marginVertical: 10 },
  progressSubtitle: { fontSize: theme.fontSize.base, color: theme.textMuted },
  toggleContainer: { flexDirection: 'row', justifyContent: 'center', marginVertical: 16, backgroundColor: theme.backgroundSecondary, borderRadius: 8, marginHorizontal: 16, overflow: 'hidden' },
  toggleButton: { flex: 1, paddingVertical: 12, alignItems: 'center' },
  toggleButtonActive: { backgroundColor: theme.primary },
  toggleButtonText: { color: theme.textMuted, fontWeight: theme.fontWeight.bold },
  toggleButtonTextActive: { color: theme.textPrimary },
  deckGroup: { marginBottom: 16, marginHorizontal: 16, backgroundColor: theme.backgroundSecondary, borderRadius: 10, overflow: 'hidden' },
  deckHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 20, backgroundColor: '#252E3D' },
  deckGroupTitle: { fontSize: theme.fontSize.md, color: theme.textPrimary, fontWeight: theme.fontWeight.bold, flex: 1 },
  noItemsText: { color: theme.textMuted, textAlign: 'center', marginTop: 40, fontSize: theme.fontSize.base },
  divider: { height: 1, backgroundColor: theme.backgroundTertiary, marginHorizontal: 20 },
  modalOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0, 0, 0, 0.6)' },
  alertModalOverlay: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0, 0, 0, 0.6)' },
  modalContent: { backgroundColor: theme.backgroundSecondary, borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 20, paddingBottom: 40 },
  modalTitle: { fontSize: theme.fontSize.lg, fontWeight: theme.fontWeight.bold, color: theme.textPrimary, textAlign: 'center', marginBottom: 20 },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  helpIcon: {
    padding: 4,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  formInputWithCounter: {
    flex: 1,
    marginRight: 8,
  },
  charCounter: {
    fontSize: theme.fontSize.caption,
    color: theme.textMuted,
    fontWeight: theme.fontWeight.semibold,
    minWidth: 45,
    textAlign: 'right',
  },
  charCounterWarning: {
    color: theme.warning,
  },
  charCounterError: {
    color: theme.danger,
  },

  // ========== MODAL FULLSCREEN ==========
  modalOverlayFullscreen: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 40,
  },
  modalContentFullscreen: {
    flex: 1,
    backgroundColor: '#141414',
    borderRadius: 24,
    padding: 20,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.07)',
    elevation: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.5,
    shadowRadius: 16,
  },
  modalHeaderFullscreen: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitleFullscreen: {
    fontSize: theme.fontSize.xl,
    fontWeight: theme.fontWeight.bold,
    color: theme.textPrimary,
  },
  modalInputFocusedGreen: {
    borderColor: theme.primary,
    borderWidth: 0.9,
  },

  // Contadores Segmentados
  segmentedCounterContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 4,
  },
  segmentedCounterText: {
    fontSize: theme.fontSize.sm,
    fontWeight: theme.fontWeight.semibold,
  },
  segmentedCounterDivider: {
    color: theme.backgroundTertiary,
    marginHorizontal: 8,
    fontSize: theme.fontSize.sm,
  },

  // Teclado Colapsável
  keypadContainer: {
    marginTop: 16,
    marginBottom: 16,
  },
  keypadToggleRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 12,
  },
  keypadToggle: {
    backgroundColor: theme.backgroundTertiary,
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginHorizontal: 6,
  },
  keypadToggleActive: {
    backgroundColor: theme.primary,
  },
  keypadToggleText: {
    color: theme.textPrimary,
    fontWeight: theme.fontWeight.bold,
    fontSize: theme.fontSize.body,
  },
  keypadPanel: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  keypadButton: {
    backgroundColor: theme.backgroundTertiary,
    width: 48,
    height: 48,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    margin: 4,
  },
  keypadButtonDisabled: {
    opacity: 0.3,
  },
  keypadButtonText: {
    color: theme.textPrimary,
    fontSize: theme.fontSize.lg,
    fontWeight: theme.fontWeight.bold,
  },
  keypadButtonTextDisabled: {
    color: theme.textDisabled,
  },

  // Botões Fullwidth do Modal
  modalButtonFullWidth: {
    backgroundColor: theme.primary,
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: 'center',
  },
  modalButtonCancelFullWidth: {
    backgroundColor: 'transparent',
    marginTop: 12,
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  modalButtonTextFullWidth: {
    color: theme.textPrimary,
    fontSize: theme.fontSize.base,
    fontWeight: theme.fontWeight.bold,
  },

  // Input do Modal com foco verde
  modalInputWithFocus: {
    backgroundColor: '#0F0F0F',
    color: theme.textPrimary,
    borderRadius: 14,
    padding: 14,
    fontSize: theme.fontSize.md,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.1)',
  },

  modalButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: theme.info, padding: 15, borderRadius: 10, marginBottom: 10 },
  modalButtonText: { color: theme.textPrimary, fontSize: theme.fontSize.base, fontWeight: theme.fontWeight.bold, marginLeft: 10 },
  userSubjectsDividerContainer: { flexDirection: 'row', alignItems: 'center', marginHorizontal: 16, marginVertical: 10 },
  userSubjectsDivider: { flex: 1, height: 1, backgroundColor: theme.backgroundTertiary },
  userSubjectsDividerText: { color: theme.textMuted, marginHorizontal: 10, fontWeight: theme.fontWeight.bold },
  subjectRightContainer: { flexDirection: 'row', alignItems: 'center' },
  subjectOptionsButton: { paddingLeft: 16, paddingVertical: 10 },
  searchContainer: { marginHorizontal: 16, marginBottom: 8 },
  searchInput: { backgroundColor: theme.backgroundSecondary, color: theme.textPrimary, borderRadius: 8, padding: 12, fontSize: theme.fontSize.base },
  alertContent: { backgroundColor: theme.backgroundSecondary, borderRadius: 15, padding: 20, width: '80%', alignItems: 'center' },
  alertTitle: { fontSize: theme.fontSize.md, fontWeight: theme.fontWeight.bold, color: theme.textPrimary, marginBottom: 10 },
  alertMessage: { fontSize: theme.fontSize.base, color: theme.textMuted, textAlign: 'center', marginBottom: 20 },
  alertButtonContainer: { flexDirection: 'row', justifyContent: 'center', width: '100%' },
  alertButton: { borderRadius: 8, paddingVertical: 10, paddingHorizontal: 20, marginHorizontal: 10, minWidth: 80, alignItems: 'center' },
  alertConfirmButton: { backgroundColor: theme.primary },
  alertCancelButton: { backgroundColor: theme.backgroundTertiary },
  alertButtonText: { color: theme.textPrimary, fontWeight: theme.fontWeight.bold },
  progressHeader: { alignItems: 'center', marginBottom: 30, paddingTop: 50 },
  settingsSection: { marginBottom: 12, paddingHorizontal: 16, paddingTop: 12 },
  settingsSectionTitle: { fontSize: theme.fontSize.body, fontWeight: theme.fontWeight.semibold, color: theme.textMuted, marginBottom: 12, letterSpacing: 0.5 },
  settingsButton: { backgroundColor: theme.backgroundSecondary, borderRadius: 12, padding: 16, marginBottom: 12, flexDirection: 'row', alignItems: 'center' },
  switchContainer: { width: 50, height: 30, borderRadius: 15, backgroundColor: theme.backgroundTertiary, padding: 3, justifyContent: 'center' },
  switchActive: { backgroundColor: theme.success },
  switchThumb: { width: 24, height: 24, borderRadius: 12, backgroundColor: theme.textPrimary },
  switchThumbActive: { alignSelf: 'flex-end' },
  dangerButton: {},
  settingsButtonTextContainer: { marginLeft: 15, flex: 1 },
  settingsButtonTitle: { fontSize: theme.fontSize.base, color: theme.textPrimary, fontWeight: theme.fontWeight.bold },
  settingsButtonSubtitle: { fontSize: theme.fontSize.sm, color: theme.textMuted, marginTop: 2 },

  editorContainer: {
    flex: 1,
    minHeight: 150,
  },
  editorContent: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    padding: 8,
  },

  // TEXTO COMUM
  nativeInputText: {
    color: theme.textPrimary,
    fontSize: theme.fontSize.md,
    fontFamily: theme.fontFamily.serif,
    paddingVertical: 4,
    marginVertical: 0,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },

  // --- FRAÇÃO ---
  fractionContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 4,
  },
  fractionInputWrapper: {
    borderWidth: 1,
    borderColor: theme.backgroundTertiary,
    borderRadius: 4,
    backgroundColor: 'rgba(0,0,0,0.2)',
    minWidth: 24,
    minHeight: 24,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  fractionInput: {
    color: theme.textPrimary,
    fontSize: theme.fontSize.body,
    fontFamily: theme.fontFamily.serif,
    textAlign: 'center',
    padding: 0,
    margin: 0,
    minWidth: 14,
  },
  fractionLine: {
    width: '100%',
    height: 1.5,
    backgroundColor: theme.textPrimary,
    marginVertical: 2,
  },

  // --- RAIZ ---
  rootContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    marginRight: 4,
    marginLeft: 2,
  },
  rootSymbolWrapper: {
    justifyContent: 'flex-end',
    marginBottom: -6,
    marginRight: -2,
  },
  rootSymbolText: {
    color: theme.textPrimary,
    fontSize: theme.fontSize.title,
    fontFamily: theme.fontFamily.serif,
    fontWeight: theme.fontWeight.light,
  },
  rootContentWrapper: {
    borderTopWidth: 1.5,
    borderTopColor: theme.textPrimary,
    paddingTop: 2,
    paddingLeft: 2,
    paddingRight: 2,
    marginBottom: 5,
  },
  rootInput: {
    color: theme.textPrimary,
    fontSize: theme.fontSize.md,
    fontFamily: theme.fontFamily.serif,
    padding: 0,
    margin: 0,
    minWidth: 10,
    textAlign: 'center',
  },

  // Multi-select styles
  checkboxContainer: {
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectedDeckItem: {
    backgroundColor: theme.primaryTransparent,
    borderColor: theme.primary,
    borderWidth: 1,
  },

  cursor: {
    width: 2,
    height: 16,
    backgroundColor: theme.primary,
  },

});

export default styles;
